### ISSUE TITLE
Add tests for permission-limited operations

### ISSUE THREAD

**Issue by aaronwolen** [aaronwolen/osfr#15]
From Courtney:

> running into an odd...lack of error with osf_component_delete: create a project, create a component, add someone else as an admin on the component and move yourself to read/write
> on the website you no longer have the ability to delete the component
> my guess is that this is some bug on the API side, but if someone else could try and recreate this just to make sure it's happening other places before I report it that would be great

**Comment by csoderberg** [comment]
I put in a bug report on our end, as I think this is an issue with the OSF API, rather than the osfr package. I'll add updates as they come in

**Comment by csoderberg** [comment]
Yep, it's a bug on our end. PR to fix it is currently in code review, so once that it through it should return the expected 403 error (this is returned already when a read contributor attempts to delete).

**Comment by aaronwolen** [comment]
Okay, then I'll close for now. Thanks for the thorough testing!
